export const SEARCH_SKILLS_REQUEST = 'SEARCH_SKILLS_REQUEST';
export const SEARCH_SKILLS_FAILURE = 'SEARCH_SKILLS_FAILURE';
export const SEARCH_SKILLS_SUCCESS = 'SEARCH_SKILLS_SUCCESS';
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const DOWNLOAD_SERVICES_REQUEST = 'DOWNLOAD_SERVICES_REQUEST';
export const DOWNLOAD_SERVICES_SUCCESS = 'DOWNLOAD_SERVICES_SUCCESS';
export const DOWNLOAD_SERVICES_FAILURE = 'DOWNLOAD_SERVICES_FAILURE';
export const DOWNLOAD_SERVICES_INIT_STATE = 'DOWNLOAD_SERVICES_INIT_STATE';